FROM python:3.11-slim   

WORKDIR /app

COPY src/Services/AI/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/Services/AI .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]